-- Couple Site MySQL Schema
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS cp_config (
  id TINYINT NOT NULL PRIMARY KEY DEFAULT 1,
  name1 VARCHAR(64) NOT NULL DEFAULT '男神',
  name2 VARCHAR(64) NOT NULL DEFAULT '女神',
  love_date DATE NOT NULL DEFAULT '2024-01-01',
  site_title VARCHAR(128) NOT NULL DEFAULT '',
  beian VARCHAR(255) NOT NULL DEFAULT '',
  avatar1 VARCHAR(255) NOT NULL DEFAULT '',
  avatar2 VARCHAR(255) NOT NULL DEFAULT '',
  background_image VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cp_visit (
  id TINYINT NOT NULL PRIMARY KEY DEFAULT 1,
  total INT UNSIGNED NOT NULL DEFAULT 0,
  today INT UNSIGNED NOT NULL DEFAULT 0,
  visit_date DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cp_about (
  id TINYINT NOT NULL PRIMARY KEY DEFAULT 1,
  version VARCHAR(64) NOT NULL DEFAULT '',
  version_desc TEXT,
  boy_name VARCHAR(64) NOT NULL DEFAULT '',
  boy_intro TEXT,
  girl_name VARCHAR(64) NOT NULL DEFAULT '',
  girl_intro TEXT,
  boy_avatar_url VARCHAR(255) NOT NULL DEFAULT '',
  girl_avatar_url VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cp_admin (
  id TINYINT NOT NULL PRIMARY KEY DEFAULT 1,
  username VARCHAR(64) NOT NULL DEFAULT 'admin',
  password VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cp_users (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) NOT NULL DEFAULT '',
  avatar VARCHAR(255) NOT NULL DEFAULT '',
  avatar_color VARCHAR(16) NOT NULL DEFAULT '#d4786e',
  created_at DATETIME NOT NULL,
  UNIQUE KEY uk_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cp_posts (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  title VARCHAR(200) NOT NULL DEFAULT '',
  tags TEXT NULL,
  content TEXT NOT NULL,
  author VARCHAR(8) NOT NULL DEFAULT '1',
  mood VARCHAR(16) NOT NULL DEFAULT '💕',
  created_at DATETIME NOT NULL,
  images TEXT NULL,
  video VARCHAR(255) NOT NULL DEFAULT '',
  music VARCHAR(255) NOT NULL DEFAULT '',
  ip VARCHAR(64) NOT NULL DEFAULT '',
  location VARCHAR(128) NOT NULL DEFAULT '',
  user_id VARCHAR(32) NULL,
  user_nick VARCHAR(64) NULL,
  user_color VARCHAR(16) NULL,
  KEY idx_created (created_at),
  KEY idx_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cp_comments (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  post_id VARCHAR(32) NOT NULL,
  nick VARCHAR(64) NOT NULL,
  text TEXT NOT NULL,
  ip VARCHAR(64) NOT NULL DEFAULT '',
  user_id VARCHAR(32) NULL,
  created_at DATETIME NOT NULL,
  KEY idx_post (post_id),
  KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cp_photos (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  url VARCHAR(255) NOT NULL,
  title VARCHAR(200) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cp_places (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  note TEXT,
  image VARCHAR(255) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cp_todos (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  note TEXT,
  done TINYINT(1) NOT NULL DEFAULT 0,
  done_time VARCHAR(32) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cp_pages (
  id VARCHAR(32) NOT NULL PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  slug VARCHAR(64) NOT NULL,
  icon VARCHAR(16) NOT NULL DEFAULT '📄',
  content MEDIUMTEXT,
  sort INT NOT NULL DEFAULT 99,
  created_at DATETIME NOT NULL,
  UNIQUE KEY uk_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO cp_config (id) VALUES (1);
INSERT IGNORE INTO cp_visit (id, total, today, visit_date) VALUES (1, 0, 0, CURDATE());
INSERT IGNORE INTO cp_about (id) VALUES (1);

SET FOREIGN_KEY_CHECKS = 1;
